### ISSUE TITLE
'No query results for model [App\User].'

### ISSUE THREAD

**Issue by nclaveras** [adamwathan/eloquent-oauth#90]
Everything was working fine, actually when users already in the system they can login, but new users I am getting following error:

[2017-11-15 19:43:24] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [App\User].' in /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:151
Stack trace:
#0 [internal function]: Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(283): call_user_func_array(Array, Array)
#2 /var/www/html/doctor2/vendor/adamwathan/eloquent-oauth/src/UserStore.php(25): Illuminate\Database\Eloquent\Relations\Relation->__call('firstOrFail', Array)
#3 /var/www/html/doctor2/vendor/adamwathan/eloquent-oauth/src/UserStore.php(25): Illuminate\Database\Eloquent\Relations\BelongsTo->firstOrFail()
#4 /var/www/html/doctor2/vendor/adamwathan/eloquent-oauth/src/Authenticator.php(48): AdamWathan\EloquentOAuth\UserStore->findByIdentity(Object(AdamWathan\EloquentOAuth\OAuthIdentity))
#5 /var/www/html/doctor2/vendor/adamwathan/eloquent-oauth/src/Authenticator.php(27): AdamWathan\EloquentOAuth\Authenticator->getExistingUser('google', Object(SocialNorm\User))
#6 /var/www/html/doctor2/vendor/adamwathan/eloquent-oauth/src/Authenticator.php(18): AdamWathan\EloquentOAuth\Authenticator->getUser('google', Object(SocialNorm\User))
#7 /var/www/html/doctor2/vendor/adamwathan/eloquent-oauth/src/OAuthManager.php(24): AdamWathan\EloquentOAuth\Authenticator->login('google', Object(SocialNorm\User), NULL)
#8 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(210): AdamWathan\EloquentOAuth\OAuthManager->login('google')
#9 /var/www/html/doctor2/app/Http/routes.php(620): Illuminate\Support\Facades\Facade::__callStatic('login', Array)
#10 /var/www/html/doctor2/app/Http/routes.php(620): AdamWathan\EloquentOAuth\Facades\OAuth::login('google')
#11 [internal function]: App\Providers\RouteServiceProvider->{closure}('google')
#12 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Routing/Route.php(157): call_user_func_array(Object(Closure), Array)
#13 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Routing/Route.php(129): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#14 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#21 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /var/www/html/doctor2/app/Http/Middleware/Language.php(17): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\Language->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/doctor2/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /var/www/html/doctor2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#44 /var/www/html/doctor2/public_html/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

Routes

Route::get ( '{provider}/authorize', function ($provider) {
	return SocialAuth::authorize ( $provider );
} );

Route::get ( '{provider}/login', function ($provider) {
	try {
		SocialAuth::login ( $provider, function ($user, $details) {
			$exists = \DB::table ( 'users' )->where ( 'email', '=', $details->email)->get ();			
			if($exists){		
			}
			else{
			$user->name = $details->full_name;
			$user->email = $details->email;
			$user->active = 1;
			$user->save ();
			$path = public_path () . '/filemanager/userfiles/' . $user->id;
			$file = \File::makeDirectory ( $path, $mode = 0777, true, true );
			$user->domain = $user->id;
			$user->newdomain = $user->id;
			$user->save ();
			$style = new Style ();
			$style->user_id = $user->id;
			$style->save ();
			}		
		} );
	} catch ( ApplicationRejectedException $e ) {
		// User rejected application
	} catch ( InvalidAuthorizationCodeException $e ) {
		// Authorization was attempted with invalid
		// code,likely forgery attempt
	}	
	// Current user is now available via Auth facade	
	$user = Auth::user ();	
	return Redirect::intended ();
} );

**Comment by nclaveras** [comment]
Solved, user previously stored but removed from users table but not from oauth table
